# Generated by Django 5.0.1 on 2024-01-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@e-mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='r_password',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
