# Generated by Django 5.0.1 on 2024-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_song_user_email_user_r_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cluster',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
