# Generated by Django 5.0.1 on 2024-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_song_cluster_song_num_song_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(),
        ),
    ]
