# Generated by Django 5.0.1 on 2024-04-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_song_id_song_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='cluster',
            new_name='clusters',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song_title',
        ),
    ]
